### ISSUE TITLE
Leaked instances

### ISSUE THREAD

**Issue by quanixstudio** [cengiz-pz/godot-android-admob-plugin#7]
When testing ads on my android phone I get the following after closing the app.

05-04 23:06:33.134 15796 15841 E godot   : USER WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
05-04 23:06:33.134 15796 15841 E godot   :    at: cleanup (core/object/object.cpp:2209)
05-04 23:06:33.134 15796 15841 I godot   : Leaked instance: JNISingleton:2264924289
05-04 23:06:33.134 15796 15841 I godot   : Leaked instance: GDScriptNativeClass:9223372047659303487
05-04 23:06:33.134 15796 15841 I godot   : Leaked instance: GDScript:9223372062909793414 - Resource path: res://addons/AdmobPlugin/model/InitializationStatus.gd
05-04 23:06:33.134 15796 15841 I godot   : Leaked instance: GDScript:9223372063278892184 - Resource path: res://addons/AdmobPlugin/model/AdmobConfig.gd
05-04 23:06:33.134 15796 15841 I godot   : Leaked instance: Object:36926653821
05-04 23:06:33.134 15796 15841 I godot   : Leaked instance: Object:36943431040
05-04 23:06:33.134 15796 15841 I godot   : Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
05-04 23:06:33.155 15796 15841 E godot   : USER ERROR: Resources still in use at exit (run with --verbose for details).
05-04 23:06:33.155 15796 15841 E godot   :    at: clear (core/io/resource.cpp:492)
05-04 23:06:33.155 15796 15841 I godot   : Resource still in use: res://addons/AdmobPlugin/model/InitializationStatus.gd (GDScript)
05-04 23:06:33.155 15796 15841 I godot   : Resource still in use: res://addons/AdmobPlugin/model/AdmobConfig.gd (GDScript)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: remove_banner_ad (static: 0, total: 1)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: load_consent_form (static: 0, total: 1)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: update_consent_info (static: 0, total: 1)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: get_smart_banner_size (static: 0, total: 1)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: get_banner_height (static: 0, total: 1)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: get_current_adaptive_banner_size (static: 0, total: 1)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: _setup_local_to_scene (static: 0, total: 2)
05-04 23:06:33.155 15796 15841 I godot   : Orphan StringName: get_initialization_status (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: load_interstitial_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: set_request_configuration (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: move_banner_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: show_rewarded_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: hide_banner_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: get_consent_status (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: show_interstitial_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: show_consent_form (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: load_rewarded_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: remove_rewarded_interstitial_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: Music (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: AdmobConfig (static: 0, total: 2)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: get_banner_height_in_pixels (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: InitializationStatus (static: 0, total: 2)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: reset_consent_info (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: remove_rewarded_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: _data (static: 0, total: 6)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: resize_banner_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: show_banner_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: remove_interstitial_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: get_landscape_adaptive_banner_size (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: load_banner_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: initialize (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: Object (static: 2, total: 3)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: get_banner_width_in_pixels (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: get_banner_width (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: is_consent_form_available (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: load_rewarded_interstitial_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: show_rewarded_interstitial_ad (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : Orphan StringName: get_portrait_adaptive_banner_size (static: 0, total: 1)
05-04 23:06:33.156 15796 15841 I godot   : StringName: 38 unclaimed string names at exit.

Am I doing something wrong?

**Comment by cengiz-pz** [comment]
Hi @quanixstudio, what Godot version are you running?  The "Orphan StringName" errors should have been fixed in Godot v4.2 as stated in https://github.com/godotengine/godot/issues/73554.

**Comment by quanixstudio** [comment]
I'm using v4.2.2.stable.official

**Comment by cengiz-pz** [comment]
Hi @quanixstudio, I have just updated the 2.0 release (same link) and the plugin model should be handled by Godot's garbage collector now.  Could you please let me know if your issues are fixed?

**Comment by quanixstudio** [comment]
With the update I still get issues

05-07 21:45:53.309 12944 13019 E godot   : USER WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
05-07 21:45:53.309 12944 13019 E godot   :    at: cleanup (core/object/object.cpp:2209)
05-07 21:45:53.309 12944 13019 I godot   : Leaked instance: JNISingleton:2264924289
05-07 21:45:53.309 12944 13019 I godot   : Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: remove_banner_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: load_consent_form (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: update_consent_info (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_smart_banner_size (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_banner_height (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_current_adaptive_banner_size (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_initialization_status (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: load_interstitial_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: set_request_configuration (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: move_banner_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: show_rewarded_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: hide_banner_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_consent_status (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: show_interstitial_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: show_consent_form (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: load_rewarded_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: remove_rewarded_interstitial_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_banner_height_in_pixels (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: reset_consent_info (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: remove_rewarded_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: resize_banner_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: show_banner_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: remove_interstitial_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_landscape_adaptive_banner_size (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: load_banner_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: initialize (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_banner_width_in_pixels (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_banner_width (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: is_consent_form_available (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: load_rewarded_interstitial_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: show_rewarded_interstitial_ad (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : Orphan StringName: get_portrait_adaptive_banner_size (static: 0, total: 1)
05-07 21:45:53.351 12944 13019 I godot   : StringName: 32 unclaimed string names at exit.

But I found out that I have these messages with every plugin I use.
As soon as I run it on an android phone (tried mutliple physical devices) I get the messages on closing the app.

Even tried this plugin on an empty project and still get the messages.

**Comment by quanixstudio** [comment]
Also for me the 'interstitial_ad_dismissed_full_screen_content' signal is not emitted when I close the ad.
I got listeners on all of the interstitial signals and only the following signals are shown in logcat:

AdMob: _on_admob_initialization_completed

AdMob: _on_admob_interstitial_ad_loaded: ca-app-pub-3940256099942544/1033173712-1
AdMob: _on_admob_interstitial_ad_showed_full_screen_content: ca-app-pub-3940256099942544/1033173712-1
AdMob: _on_admob_interstitial_ad_impression: ca-app-pub-3940256099942544/1033173712-1
AdMob: _on_admob_interstitial_ad_clicked: ca-app-pub-3940256099942544/1033173712-1

---- EDIT ----

I found that the problem is in the SignalInfo

signals.add(new SignalInfo(SIGNAL_INTERSTITIAL_AD_DISMISSED_FULL_SCREEN_CONTENT, String.class, Dictionary.class));

should be

signals.add(new SignalInfo(SIGNAL_INTERSTITIAL_AD_DISMISSED_FULL_SCREEN_CONTENT, String.class));

without the Dictionary since it does only send a String.

**Comment by quanixstudio** [comment]
I added the issue on the godotengine git because I don't think the leaks have anything to do with your plugin.

[https://github.com/godotengine/godot/issues/91739](https://github.com/godotengine/godot/issues/91739)

**Comment by cengiz-pz** [comment]
Closing this issue as https://github.com/godotengine/godot/issues/91739 was closed.
